### PR TITLE
Generate .jrubydir just-in-time for packing the JRubyJar archive

### PR DESCRIPTION
**Pull request by rtyler**

### CODE REVIEW

**Comment by rtyler** [comment]
@mkristian has taken a first pass at this, and pending travis going green I think I'm going to merge it since @ysb33r is so busy as of late :(

**Comment by rtyler** [comment]
Well I'll be damned, another set of changes which only seem to fail in Travis CI. I'm thinking it might be time to disable the caching of ~/.gradle

**Comment by mkristian** [comment]
@rtyler did you find the actual error on travis ? I just see an failed at the end but nothing in between.

**Comment by rtyler** [comment]
@mkristian I've seen the error a few times, it's always deep in the console log. Basically the embedded jetty throwing a 500 on some requests during a gradleTest. I'm trying to get a local reproduction case

**Pull request merged**
