### PR TITLE
Adjust some settings to hopefully get Travis to stop failing builds :hankey:

### PR DESCRIPTION
**Pull request by rtyler**

### CODE REVIEW

**Comment by mkristian** [comment]
oh it is the rubygems servlet which gives the problem :(

any news or changes on the gradle side to implement this in inline manner via custom protocol handler or something ?

**Comment by rtyler** [comment]
@mkristian I'm not sure what specifically is causing this problem. I cannot get any test failures locally no matter how hard I try 😦 

I think the parallelism of my local machine, or speed of my local machine compared to Travis, might be the cause.

**Comment by rtyler** [comment]
Alright, my research suggests that this is having an `OutOfMemory` error in Travis.

FUN.

**Comment by mkristian** [comment]
what I do sometimes is to split the build in two travis jobs: one with all the tests which already work on one job and excluding the others and a second travis job inverting the include/exclude of tests

**Comment by rtyler** [comment]
I think these are reasonable settings to have nonetheless, I might just drop Travis CI entirely really soon here.

**Pull request merged**
