### PR TITLE
This is a rebase of #283 on top of the latest master

### PR DESCRIPTION
**Pull request by rtyler**
Closes #283

### CODE REVIEW

**Comment by ysb33r** [comment]
If you leave the Appveyor build with a JDK7 build then there should be adequate average. 

If you really want to drop JDK7 covreage bump the build to set `(source|target)Compatility` to `1.8`. Publish it explicitely that it requires JDK8.

**Comment by rtyler** [comment]
@ysb33r Java 7 is so end of lifed it's almost as bad as Ruby 1.9.3 now :smile_cat: 

I don't want to waste what little time I can spend on this project dealing with supremely out of date environments.

**Comment by ysb33r** [comment]
Force it to build for 1.8, but let's bump the version also in such a way it reflects the compatibility break.

**Comment by rtyler** [comment]
Well, at least I've gotten to the point where I can reproduce these errors locally, so that's progress?

**Pull request closed without merging**
