### PR TITLE
Use new `mainClass` property instead of `main`

### LINKED ISSUE #427: Gradle 7.1 deprecation warnings
Running `jruby-gradle-plugin` on Gradle 7.1 leads to:

```
The JavaExecHandleBuilder.setMain(String) method has been deprecated. This is scheduled to be removed in Gradle 8.0. Please use the mainClass property instead. Consult the upgrading guide for further information: https://docs.gradle.org/7.1/userguide/upgrading_version_7.html#java_exec_properties
        at org.gradle.process.internal.JavaExecHandleBuilder.setMain(JavaExecHandleBuilder.java:316)
        at org.gradle.process.internal.JavaExecHandleBuilder.setMain(JavaExecHandleBuilder.java:60)
        at com.github.jrubygradle.api.gems.GemUtils$_extractGems_closure4$_closure10.doCall(GemUtils.groovy:143)
        at com.github.jrubygradle.api.gems.GemUtils$_extractGems_closure4$_closure10.call(GemUtils.groovy)
        at com.github.jrubygradle.api.gems.GemUtils$_extractGems_closure4.doCall(GemUtils.groovy:134)
        ...
```

### PR DESCRIPTION
**Pull request by donv**
This should remove the deprecation warning and fix #427 .

### CODE REVIEW

**Comment by donv** [comment]
Any chance of getting this merged?

**Comment by boris-petrov** [comment]
cc @ysb33r

**Comment by PseudoDistant** [comment]
Just how ded is this project?
Jeez...

**Comment by PseudoDistant** [comment]
@donv sorry for bothering you, but you seem to be literally the only person doing work on this plugin, and I suck at Gradle.
https://github.com/jruby-gradle/jruby-gradle-plugin/issues/432
Do you know what can be done about this?

**Comment by donv** [comment]
I am only a contributor.  We use this plugin in our projects, and it is important to us, but we have no commit rights.

**Comment by UweKubosch** [comment]
@rtyler @ysb33r @mkristian Any chance of getting this merged?

**Comment by mkristian** [comment]
@rtyler @ysb33r I merged it as it looks sane and apparently it fixes the problem. but I can not release and deploy the whole thing, I really need you to do it.

**Pull request merged**
