### PR TITLE
Add a of conduct  from contributor-covenant.org

### LINKED ISSUE #173: A project code of conduct should be added
I'm fearful of opening up a can of worms here since I've not done something like this before, and I realize how polarizing this topic can be for some people.

I'll have to enlist the help of either @lhawthorn or @nudibranch to make sure we get this right.

### PR DESCRIPTION
**Pull request by rtyler**
This seems reasonable enough

Fixes #173

### CODE REVIEW

**Comment by rtyler** [comment]
@mkristian @ysb33r please chime in with your thoughts on this.

**Comment by mkristian** [comment]
good for me. a bit sad that you need something I consider common sense. but I guess I miss the real world sometime :)

**Comment by rtyler** [comment]
@mkristian I agree that these are common sense, to me, but the goal is to ensure that contributors have a shared understanding of what is expected. It also gives us a tool later on, if need be, to ask somebody who is toxic to the community to leave.

**Comment by ysb33r** [comment]
I'm good with this.

**Comment by CoralineAda** [comment]
Thanks!

**Pull request merged**
