### PR TITLE
Bump the to the latest JRuby version of 9.2.7.0

### PR DESCRIPTION
**Pull request by rtyler**

### CODE REVIEW

**Comment by rtyler** [comment]
The failure in the tests is quite interesting:

```
ERROR:  While executing gem ... (Gem::Package::PathError)
        installing into parent path /home/travis/build/jruby-gradle/jruby-gradle-plugin/jruby-gradle-base-plugin/build/tmp/integrationTest/root/jpgis/rack-resolve/build/gems/gems/sinatra-1.4.5 of /home/travis/build/jruby-gradle/jruby-gradle-plugin/jruby-gradle-base-plugin/build/tmp/integrationTest/root/jpgis/rack-resolve/build/gems/gems/sinatra-1.4.5 is not allowed
```

It's not immediately clear what this could be.

**Comment by rtyler** [comment]
This _looks_ like an issue which occurred with rubygems 2.5 a while back, but as far as I can tell everything from 9.1.14.0 onwards has rubygems 2.6 embedded.

https://github.com/rubygems/rubygems/issues/1448

:thinking:

**Comment by rtyler** [comment]
I haven't  been able to figure out how to set the `--info` flag for the project in the integration test, so I'm not sure what command exactly is running here.

When I try to use `jruby-complete.jar` to install the same gems in the test failure, that all works fine, even with the same arguments..

:thinking:

**Comment by rtyler** [comment]
From discussion with @headius , it looks like the issue might revolve around a Rubygems security fix. This error is reproducible on 9.1.16.0 but not 9.1.15.0.

There was a Rubygems release change between them (2.6.14) which was to fix a security issue around symbolic links on the file system. https://bugs.ruby-lang.org/issues/14481


Some other interesting links:

* Tests for this behavior: https://github.com/ruby/ruby/commit/4237809aa3983fca36b520f95b48fdf9e7e88de2#diff-7d891128874ea0e4a2f0c3b809ee2c87R458
*  Where the error is likely coming from: https://github.com/ruby/ruby/commit/4237809aa3983fca36b520f95b48fdf9e7e88de2#diff-3a0baa1500616100ad7469f0f7b20c3cL427


My current theory is that this is only failing in our integration test environment, and doesn't fail with a manual test, because of the constructed file tree we use for integration testing.

**Comment by ysb33r** [comment]
I suspect the fact that the `data.tar.gz` inside the `lookout-rack-utils` GEM v3.1.0.12 is empty is the root cause of the test failure. Replace that with v5.0.0.49and the test issue might just disappear.

**Pull request merged**
