### PR TITLE
Fix range check for string versions

### LINKED ISSUE #267: Can't resolve latest version of a dependency (e.g 'rubygems:colorize:+')
Ran into this problem trying to upgrade to version 1.2.0 of jruby-gradle-plugin in another project that depends on it; that project uses a dependency in this format: 'rubygems:compass:+'.  With jruby 1.2.0 I get an exception from gradle trying to resolve dependencies.  I was able to reproduce the exception with this build.gradle:

``` gradle

import com.github.jrubygradle.JRubyExec

buildscript {
   repositories { jcenter() }

  dependencies {
    classpath "com.github.jruby-gradle:jruby-gradle-plugin:1.2.0"
  }
}

apply plugin: "com.github.jruby-gradle.base"

dependencies {
  jrubyExec "rubygems:colorize:+"
}

task printSomePrettyOutputPlease(type: JRubyExec) {
  description "Execute our nice local print-script.rb"
  script "${projectDir}/print-script.rb"
}
```
Attempting to run the printSomePrettyOutputPlease task will give this exception resolving dependencies:
```
Caused by: org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object '' with class 'java.lang.String' to class 'int'
	at com.github.jrubygradle.internal.GemVersion.compare(GemVersion.groovy:182)
	at com.github.jrubygradle.internal.GemVersion.conflict(GemVersion.groovy:202)
	at com.github.jrubygradle.internal.GemVersion$conflict$0.call(Unknown Source)
	at com.github.jrubygradle.internal.GemVersionResolver.resolve(GemVersionResolver.groovy:74)
	at com.github.jrubygradle.internal.GemVersionResolver$_closure1_closure4.doCall(GemVersionResolver.groovy:28)
	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
	at org.gradle.api.internal.artifacts.ivyservice.dependencysubstitution.DefaultDependencySubstitutions$DependencyResolveDetailsWrapperAction.execute(DefaultDependencySubstitutions.java:193)
	at org.gradle.api.internal.artifacts.ivyservice.dependencysubstitution.DefaultDependencySubstitutions$DependencyResolveDetailsWrapperAction.execute(DefaultDependencySubstitutions.java:183)
	at org.gradle.internal.Actions$CompositeAction.execute(Actions.java:76)
	at org.gradle.internal.Actions$CompositeAction.execute(Actions.java:76)
	at org.gradle.api.internal.artifacts.ivyservice.dependencysubstitution.DependencySubstitutionResolver.resolve(DependencySubstitutionResolver.java:40)
	... 110 more
```
It looks like there is a straightforward fix in GemVersion.groovy (it is trying to cast to an int variable after testing to see that the string is not an int).  Not sure if this case should be caught upstream though.

### PR DESCRIPTION
**Pull request by michaelwoodson**
Fixes #267

### CODE REVIEW

**Comment by rtyler** [comment]
The test failures do look correct on this, appears to be some integration tests in `com.github.jrubygradle.JRubyPrepareGemsIntegrationSpec`

**Comment by rtyler** [comment]
@mkristian if you wouldn't mind reviewing this if you get the chance, I think you're a bit more familiar with the `GemVersion` code than I am :P

**Comment by mkristian** [comment]
the code patched are OK

travis complains about codenarc - @michaelwoodson could you see those codenarc locally - can not be much, probably just an overly strict style rule ;)

**Comment by rtyler** [comment]
@mkristian I see in the Travis log:

```
com.github.jrubygradle.JRubyPrepareGemsIntegrationSpec > Check if rack version gets resolved FAILED
```

For example,. I think there are test failures as well.

**Comment by mkristian** [comment]
@rtyler right - did not see those

**Comment by michaelwoodson** [comment]
Sorry, I noticed the build problem this morning and pushed a fix for the codenarc issue.  I was able to successfully build locally with the same command being used by travis `./gradlew -S -i check gradleTest assemble` before I pushed.  It looks like the build worked on openjdk7 but not openjdk8, not sure if jvm is really the issue though.  The test that is failing could be impacted by the change in the pr (non-int revision being used), just need to reproduce it.  I was using an oracle 8 vm; still investigating...

**Comment by michaelwoodson** [comment]
Looks like the same thing happened for a different PR 2 months ago:
https://travis-ci.org/jruby-gradle/jruby-gradle-plugin/jobs/99627183

Since I haven't been able to reproduce locally I don't think those issues are related to this change.  I did confirm that travis is in fact using an oracle 8 vm (1.8.0_31).  I have 1.8.0_40.

**Comment by mkristian** [comment]
@michaelwoodson OK it is time to find the problem with broken build on this PR and the other PR you mentioned. I never was able to reproduce it locally - same as you. but it prevents both PR to be merged :)

I will find some time tomorrow for it - thanx so far

**Comment by rtyler** [comment]
I retriggered the build on JDK8 *crosses fingers*

**Comment by michaelwoodson** [comment]
Sounds good.  Researched a little and it sounds like the default oracle jdk 8 is quite old and buggy on travis, if I'm reading this right you could try forcing a more recent one as a longshot:
https://github.com/travis-ci/travis-ci/issues/3259

Thanks!

**Comment by rtyler** [comment]
@michaelwoodson If you update your PR to attempt to force a later JDK, I won't mind :)

**Comment by rtyler** [comment]
OMGOMGOMG IT'S GREEN, MERGE IT BEFORE TRAVIS REALIZES WHAT HAPPENED

**Comment by rtyler** [comment]
xD

**Comment by michaelwoodson** [comment]
Phew, we did it reddit! :+1:

**Pull request merged**
